### ISSUE TITLE
Hello! why discriminator dense layer have num_class+1?

### ISSUE THREAD

**Issue by zychen2016** [nejlag/Semi-Supervised-Learning-GAN#4]

**Comment by nejlag** [comment]
In a vanilla GAN, the discriminator (D) which is a classifier has two outputs: one output for real samples and one output for fake samples. 

Now, in semi-supervised learning, the output for real samples is replaced with num_class outputs as we have labels for some of the real samples (note: real samples belong to one of num_class classes) and we want to take advantage of them. So, in total, the discriminator (D) should have num_class+1 outputs.
